@HtmxAppServer_HostAddress = http://localhost:5004

### App
GET {{HtmxAppServer_HostAddress}}/
Accept: text/html

### Examples Dashboard
GET {{HtmxAppServer_HostAddress}}/ui/examples
Accept: text/html

### Counter Example
@count = 5
GET {{HtmxAppServer_HostAddress}}/ui/examples/counter?Count={{count}}
Accept: text/html

### Live Search
GET {{HtmxAppServer_HostAddress}}/ui/examples/live-search?Query=luke
Accept: text/html
