using FastComponents.Generators.Helpers;
using Shouldly;

namespace FastComponents.Generators.UnitTests;

/// <summary>
/// Tests for the IndentedCodeBuilder helper class.
/// </summary>
public class IndentedCodeBuilderTests
{
    [Fact]
    public void Line_AppendsTextWithNewline()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Line("var x = 1;");

        // Assert
        builder.ToString().ShouldContain("var x = 1;");
    }

    [Fact]
    public void EmptyLine_AddsBlankLine()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Line("first");
        builder.EmptyLine();
        builder.Line("second");

        // Assert
        string result = builder.ToString();
        result.ShouldContain("first");
        result.ShouldContain("second");
        // Should have an empty line between them
        result.Split('\n').Count(l => l.Trim().Length == 0).ShouldBeGreaterThan(0);
    }

    [Fact]
    public void Comment_AddsDoubleSlashPrefix()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Comment("This is a comment");

        // Assert
        builder.ToString().ShouldContain("// This is a comment");
    }

    [Fact]
    public void Braces_WrapsContentInBraces()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Braces(() => builder.Line("content;"));

        // Assert
        string result = builder.ToString();
        result.ShouldContain("{");
        result.ShouldContain("content;");
        result.ShouldContain("}");
    }

    [Fact]
    public void Braces_WithSuffix_AppendsSuffixAfterClosingBrace()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Braces(() => builder.Line("content;"), ";");

        // Assert
        builder.ToString().ShouldContain("};");
    }

    [Fact]
    public void Indent_IncreasesIndentation()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Line("outer");
        builder.Indent(() => builder.Line("inner"));
        builder.Line("outer again");

        // Assert
        string result = builder.ToString();
        string[] lines = result.Split('\n', StringSplitOptions.RemoveEmptyEntries);

        // The indented line should start with spaces
        string innerLine = lines.First(l => l.TrimStart().StartsWith("inner", StringComparison.Ordinal));
        innerLine.ShouldStartWith("    "); // 4-space indent
    }

    [Fact]
    public void Summary_GeneratesXmlDocComment()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Summary("A test summary");

        // Assert
        string result = builder.ToString();
        result.ShouldContain("/// <summary>");
        result.ShouldContain("/// A test summary");
        result.ShouldContain("/// </summary>");
    }

    [Fact]
    public void SummaryParam_GeneratesParamDocComment()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.SummaryParam("value", "The input value");

        // Assert
        builder.ToString().ShouldContain("/// <param name=\"value\">The input value</param>");
    }

    [Fact]
    public void CommentAutoGenerated_GeneratesAutoGenComment()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.CommentAutoGenerated();

        // Assert
        string result = builder.ToString();
        result.ShouldContain("// <auto-generated />");
    }

    [Fact]
    public void NestedBraces_MaintainProperIndentation()
    {
        // Arrange
        IndentedCodeBuilder builder = new();

        // Act
        builder.Line("namespace Test");
        builder.Braces(() =>
        {
            builder.Line("public class Foo");
            builder.Braces(() => builder.Line("// body"));
        });

        // Assert
        string result = builder.ToString();
        result.ShouldContain("namespace Test");
        result.ShouldContain("public class Foo");
        result.ShouldContain("// body");
    }

    [Fact]
    public void ToString_ReturnsBuiltString()
    {
        // Arrange
        IndentedCodeBuilder builder = new();
        builder.Line("test");

        // Act
        string result = builder.ToString();

        // Assert
        result.ShouldNotBeNullOrEmpty();
    }
}
