using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using FastComponents.Generators.Helpers;

namespace FastComponents.Generators;

/// <summary>
/// Source generator that generates BuildQueryString and BindFromQuery methods for records decorated with [GenerateParameterMethods] attribute.
/// </summary>
[Generator]
public class HtmxParametersGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all records with GenerateParameterMethods attribute
        IncrementalValuesProvider<GeneratorTarget> provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsSyntaxTargetForGeneration(node),
                transform: static (context, _) => GetSemanticTargetForGeneration(context))
            .Where(static target => target is not null)
            .Select(static (target, _) => target!);

        // Generate source for each record
        context.RegisterSourceOutput(
            provider,
            static (context, target) =>
            {
                string source = GenerateParameterMethods(target);
                if (string.IsNullOrEmpty(source))
                {
                    return;
                }

                context.AddSource($"{target.Symbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
            });
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is RecordDeclarationSyntax record && record.AttributeLists.Count > 0;
    }

    private static GeneratorTarget? GetSemanticTargetForGeneration(in GeneratorSyntaxContext context)
    {
        var recordSyntax = (RecordDeclarationSyntax)context.Node;
        INamedTypeSymbol? symbol = context.SemanticModel.GetDeclaredSymbol(recordSyntax);

        if (symbol is not { } namedTypeSymbol)
        {
            return null;
        }

        // Check if it has GenerateParameterMethods attribute
        AttributeData? attribute = namedTypeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "GenerateParameterMethodsAttribute"
                || a.AttributeClass?.ToDisplayString() == "FastComponents.GenerateParameterMethodsAttribute");

        if (attribute is null)
        {
            return null;
        }

        // Get SkipDefaults property value
        var skipDefaults = true; // default value
        if (attribute.NamedArguments.Length > 0)
        {
            KeyValuePair<string, TypedConstant> skipDefaultsArg = attribute.NamedArguments.FirstOrDefault(arg => arg.Key == "SkipDefaults");
            if (skipDefaultsArg.Key is not null && skipDefaultsArg.Value.Value is bool skipDefaultsValue)
            {
                skipDefaults = skipDefaultsValue;
            }
        }

        // Check if it inherits from HtmxComponentParameters
        INamedTypeSymbol? baseType = namedTypeSymbol.BaseType;
        while (baseType is not null)
        {
            if (baseType.Name == "HtmxComponentParameters"
                && baseType.ContainingNamespace.ToDisplayString() == "FastComponents")
            {
                return new GeneratorTarget(namedTypeSymbol, recordSyntax, skipDefaults);
            }

            baseType = baseType.BaseType;
        }

        return null;
    }

    private static string GenerateParameterMethods(GeneratorTarget target)
    {
        INamedTypeSymbol symbol = target.Symbol;
        string namespaceName = symbol.ContainingNamespace.ToDisplayString();
        string className = symbol.Name;

        // Get all public properties with init accessors
        List<IPropertySymbol> properties = symbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public
                && p.SetMethod?.IsInitOnly == true)
            .ToList();

        IndentedCodeBuilder builder = new();

        // Generate file header
        builder.Comment("<auto-generated/>");
        builder.Line("#nullable enable");
        builder.EmptyLine();
        builder.Line("using FastComponents;");
        builder.Line("using Microsoft.AspNetCore.Http;");
        builder.EmptyLine();

        // Generate namespace and class
        builder.Line($"namespace {namespaceName}");
        builder.Braces(() =>
        {
            builder.Line($"public partial record {className}");
            builder.Braces(() =>
            {
                if (properties.Count == 0)
                {
                    builder.Comment("No properties found to generate methods for");
                }
                else
                {
                    // Generate BuildQueryString method
                    GenerateBuildQueryString(builder, properties, className, target.SkipDefaults);

                    builder.EmptyLine();

                    // Generate BindFromQuery method
                    GenerateBindFromQuery(builder, properties);

                    // Add helper method for bool if needed
                    if (properties.Any(p => p.Type.SpecialType == SpecialType.System_Boolean))
                    {
                        builder.EmptyLine();
                        GenerateGetQueryBoolHelper(builder);
                    }
                }
            });
        });

        return builder.ToString();
    }

    private static void GenerateBuildQueryString(
        IndentedCodeBuilder builder,
        List<IPropertySymbol> properties,
        string className,
        bool skipDefaults)
    {
        builder.Line("protected override string BuildQueryString()");
        builder.Braces(() =>
        {
            builder.Line("var parts = new System.Collections.Generic.List<string>();");
            builder.EmptyLine();

            foreach (IPropertySymbol? property in properties)
            {
                string propertyName = property.Name;
                ITypeSymbol propertyType = property.Type;

                if (propertyType.SpecialType == SpecialType.System_String)
                {
                    builder.Line($"if (!string.IsNullOrEmpty({propertyName}))");
                    builder.Braces(() =>
                    {
                        if (skipDefaults)
                        {
                            builder.Line($"var defaultValue = new {className}().{propertyName};");
                            builder.Line($"if ({propertyName} != defaultValue)");
                            builder.Indent(() => builder.Line(
                                $"parts.Add($\"{propertyName}={{System.Uri.EscapeDataString({propertyName})}}\");"));
                        }
                        else
                        {
                            builder.Line($"parts.Add($\"{propertyName}={{System.Uri.EscapeDataString({propertyName})}}\");");
                        }
                    });
                }
                else if (propertyType.SpecialType == SpecialType.System_Int32)
                {
                    if (skipDefaults)
                    {
                        builder.Braces(() =>
                        {
                            builder.Line($"var defaultValue = new {className}().{propertyName};");
                            builder.Line($"if ({propertyName} != defaultValue)");
                            builder.Indent(() => builder.Line($"parts.Add($\"{propertyName}={{{propertyName}}}\");"));
                        });
                    }
                    else
                    {
                        builder.Line($"parts.Add($\"{propertyName}={{{propertyName}}}\");");
                    }
                }
                else if (propertyType.SpecialType == SpecialType.System_Boolean)
                {
                    if (skipDefaults)
                    {
                        builder.Braces(() =>
                        {
                            builder.Line($"var defaultValue = new {className}().{propertyName};");
                            builder.Line($"if ({propertyName} != defaultValue)");
                            builder.Indent(() => builder.Line(
                                $"parts.Add($\"{propertyName}={{{propertyName}.ToString().ToLowerInvariant()}}\");"));
                        });
                    }
                    else
                    {
                        builder.Line($"parts.Add($\"{propertyName}={{{propertyName}.ToString().ToLowerInvariant()}}\");");
                    }
                }
                else
                {
                    // For other types, always include them
                    builder.Line($"if ({propertyName} != null)");
                    builder.Indent(() => builder.Line(
                        $"parts.Add($\"{propertyName}={{System.Uri.EscapeDataString({propertyName}.ToString() ?? \"\")}}\");"));
                }

                builder.EmptyLine();
            }

            builder.Line("return string.Join(\"&\", parts);");
        });
    }

    private static void GenerateBindFromQuery(IndentedCodeBuilder builder, List<IPropertySymbol> properties)
    {
        builder.Line("public override HtmxComponentParameters BindFromQuery(IQueryCollection query)");
        builder.Braces(() =>
        {
            builder.Line("return this with");
            builder.Braces(
                () =>
                {
                    for (int i = 0; i < properties.Count; i++)
                    {
                        IPropertySymbol? property = properties[i];
                        string propertyName = property.Name;
                        ITypeSymbol propertyType = property.Type;
                        bool isLast = i == properties.Count - 1;
                        string comma = isLast ? string.Empty : ",";

                        if (propertyType.SpecialType == SpecialType.System_String)
                        {
                            builder.Line($"{propertyName} = GetQueryValue(query, \"{propertyName}\") ?? {propertyName}{comma}");
                        }
                        else if (propertyType.SpecialType == SpecialType.System_Int32)
                        {
                            builder.Line($"{propertyName} = GetQueryInt(query, \"{propertyName}\") ?? {propertyName}{comma}");
                        }
                        else if (propertyType.SpecialType == SpecialType.System_Boolean)
                        {
                            builder.Line($"{propertyName} = GetQueryBool(query, \"{propertyName}\") ?? {propertyName}{comma}");
                        }
                        else
                        {
                            // For other types, keep the current value
                            builder.Line($"{propertyName} = {propertyName}{comma} // TODO: Add support for {propertyType}");
                        }
                    }
                },
                ";");
        });
    }

    private static void GenerateGetQueryBoolHelper(IndentedCodeBuilder builder)
    {
        builder.Line("private static bool? GetQueryBool(IQueryCollection query, string key)");
        builder.Braces(() =>
        {
            builder.Line("var value = GetQueryValue(query, key);");
            builder.Line("return value != null && bool.TryParse(value, out var result) ? result : null;");
        });
    }

    private record GeneratorTarget(INamedTypeSymbol Symbol, RecordDeclarationSyntax Syntax, bool SkipDefaults);
}
